### ISSUE TITLE
module error

### ISSUE THREAD

**Issue by Milan-VLIZ** [vlizBE/vocabserver-frontend#32]
Hi,

We've noticed that for the new version the module for random UUID generation is still not loaded correctly.
Clean build does not solve this either. Can you check, please?

![image](https://user-images.githubusercontent.com/80511992/227175463-778c4836-b64e-45cc-a254-b4c3939e1326.png)

Gr,
Milan

**Comment by nvdk** [comment]
Hi Milan,

Dit is mogelijk gerelateerd aan je browser(versie): https://caniuse.com/mdn-api_crypto_randomuuid . Kan je eens in een andere browser proberen?

**Comment by Milan-VLIZ** [comment]
Hi Niels,

I've checked some browsers, but they all fail on the same issue. Although the versions seem to be OK according to caniuse.com.

Chrome: 
![image](https://user-images.githubusercontent.com/80511992/228170709-bcc7eadf-cb00-4622-b5cf-34d88f11b88a.png)

Firefox:
![image](https://user-images.githubusercontent.com/80511992/228170760-58896fd6-4765-4540-a9d2-fa41ff6d7091.png)

Edge:
![image](https://user-images.githubusercontent.com/80511992/228170815-27ba11a0-dfcb-4c45-930b-930b20a9f47f.png)

We have 1 of your containers running linked to this uuid creation:
`kanselarij/uuid-generation-service:1.0.0  "docker-entrypoint.s…"   11 days ago     Up 11 days   vocabserver-app_uuid-generation_1`, I suppose this one is used for this purpose?

To me personally it looks like an js import issue or perhaps the module which has not been installed succesfully/correctly by npm? Just ideas.

Gr,
Milan

**Comment by nvdk** [comment]
We've found the issue, it's due to some obscure browser bug. When serving the app under http, the crypto module isn't available in some browsers. We've addressed this is in #35

**Comment by Milan-VLIZ** [comment]
Great, bug no longer occurs. Thanks

**Comment by nvdk** [comment]
@Milan-VLIZ could you merge the PR or give me access to merge it? :)
