### ISSUE TITLE
configured mapping for one vocab seems to set mappings for all vocabs?

### ISSUE THREAD

**Issue by marc-portier** [vlizBE/vocabserver-frontend#36]
testing on our local copy we have now added 5 different vocabs - and did so in parallel in 5 parallel tabs from the same browser session.

after 
1. adding all five  (4 being skos based -- coming from the bodc nerc vocab -- P01, P06, S25, C19)
2. initiating their download
3. starting the mapping / analysis

we ended up adding the mapping config for one (P06) like this:
![screenshot - P06 mapping](https://user-images.githubusercontent.com/299574/234271468-1d151ae3-edc7-48b3-ae02-52e47fbfad7a.png)

only to find that its analysis and mapping seems to be the one being applied to all vocabs --> similar screenshots exist for all now !

surely the "analysis" part of this state can not be equal for all of them:
![screenshot - P01 class count](https://user-images.githubusercontent.com/299574/234271855-413a47ca-76f8-4ef8-95dd-a55d5b6d2577.png)

![screenshot - P09 class count](https://user-images.githubusercontent.com/299574/234271969-f8ed40e6-ca33-44f0-9e81-15caa4a36b07.png)

and while the applied mapping is to be shared by all the skos-based vocabs, it surely does not fit the one that is not having any skos entities:

![screenshot - MRG class count](https://user-images.githubusercontent.com/299574/234272391-5cfcefc4-ed5a-4a88-8a40-7ec14cbf1bc3.png)

actually for this last one the download (ingest) has not even ended:
![screenshot - MRG home](https://user-images.githubusercontent.com/299574/234272720-d0c19727-71e0-4068-8d3d-4258f2ca7bec.png)

Maybe the info we see is based on a sparql back-end query that is not tuning into the graph/subset and giving an overall view?

But in any case the config should not be shared / inherited.

For now I have started the unification on the 4 skos based vocabs - all of them not finished after running ~20 minutes ...

**Comment by marc-portier** [comment]
and now I am totally flabergasted...

just to verify I went through the same cycle over on the test environment 
even on this totally different server this mapping config and analysis info seems to be inherited from my earlier work on our docker-dev?

![screenshot - P01 mapping](https://user-images.githubusercontent.com/299574/234275996-63b77881-809c-471f-84c9-9badfed3c105.png)

![screenshot - P01 class count](https://user-images.githubusercontent.com/299574/234276141-e59d55e0-413c-42fe-955b-42c81c8ed42a.png)

and it really seems to be fed from the server, since a provate browser session or even a totally different browser gives the same output?
![screenshot - P01 class count](https://user-images.githubusercontent.com/299574/234276651-bdb44e2e-caca-4694-8785-4e60dcb7d7c6.png)

**Comment by nvdk** [comment]
@marc-portier I believe this one can be closed?
