### ISSUE TITLE
adding bogus entries in the list of vocabs should be prevented OR status info from vocabs could be made visible in the list

### ISSUE THREAD

**Issue by marc-portier** [vlizBE/vocabserver-frontend#37]
When adding a bogus vocabulary:
![screenshot bogus vocab entry](https://user-images.githubusercontent.com/299574/234281681-d1b9bbe7-b862-45e5-bd21-ed745fc3f735.png)

It ends up in the list anyway - and upon visiting it simply shows "No Sources found"
![screenshot vocab list](https://user-images.githubusercontent.com/299574/234283496-cc6eccaf-8ca4-4fec-9ce6-a318b770a7c7.png)

![screenshot no sources](https://user-images.githubusercontent.com/299574/234282244-9bcd5c1c-4f76-4ec7-b8dd-6d9132f4c9a9.png)

If we keep this behavior it would be nice if some visual indicator in the list is warning the admin about the faulty state of this entry?

**Comment by nvdk** [comment]
@marc-portier this should be fixed, can you close if you agree?
