### ISSUE TITLE
adding new source to vocab does not allow to add type LDES

### ISSUE THREAD

**Issue by marc-portier** [vlizBE/vocabserver-frontend#39]
When using the "add source" to an existing vocab we get this form:
![image](https://user-images.githubusercontent.com/299574/234919456-21ad6b53-d135-4ecb-a965-cbc5339c385c.png)

This does not allow to add an extra LDES feed.

We think this should be possible however for these cases:
- replacing the current LDES feed because some settings (URL itself or other props like deref and max request rate) should be changed
- adding other languages that are providing an LDES feed

**Comment by nvdk** [comment]
this is included in the 1.1. release
